export { default as Navigation } from './Navigation/Navigation';
export { default as About } from './About/About';
export { default as Research } from './Research/Research';
export { default as Experience } from './Experience/Experience';
export { default as Prabha } from './Prabha/Prabha';
export { default as Gallery } from './Gallery/Gallery';
export { default as Contact } from './Contact/Contact';
export { default as Footer } from './Footer/Footer';
export { default as Loader } from './Loader/Loader';
